# Generated by Django 4.2.7 on 2024-01-03 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0001_initial'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookCountCart',
            new_name='TicketCountCart',
        ),
    ]
