# Generated by Django 4.2.7 on 2024-01-02 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=31, verbose_name='نام')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=31, verbose_name='نام مبدا')),
                ('destination', models.CharField(max_length=31, verbose_name='نام مقصد')),
                ('create_date', models.DateField(blank=True, null=True, verbose_name='تاریخ ایجاد')),
                ('last_update', models.DateTimeField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='قیمت')),
                ('flight_date', models.DateTimeField()),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='ticket.company')),
            ],
        ),
    ]
